version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: m2ao/nodejs-mysql-app
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=moe-mysql-app
      - MYSQL_USER=emeric_user
      - MYSQL_PASS=emeric_db
      - MYSQL_DB=emeric_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:5000"
    container_name: emeric-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=emeric_user
      - MYSQL_PASSWORD=emericmdp 
      - MYSQL_DATABASE=emeric_db
    container_name: emeric-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=moe-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend: